spring:
  profiles:
    active: dev

---
#开发环境配置
spring:
  profiles: dev
  application:
    name: mocroservicecloud-config-dev

server:
  port: 1000


---
#测试环境配置
spring:
  profiles: test
  application:
    name: mocroservicecloud-config

server:
  port: 1001


---
#生产环境配置
spring:
  profiles: prod
  application:
    name: mocroservicecloud-config

server:
  port: 1002
